# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - WingridAuthAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unittest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build-auth:
    runs-on: windows-latest
    needs: unittest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: cd Services/Wingrid.Services.Auth && dotnet build --configuration Release

      - name: dotnet publish
        run: cd Services/Wingrid.Services.Auth && dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/wingridAuthAPI

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: winGridAuthAPI-app
          path: ${{env.DOTNET_ROOT}}/wingridAuthAPI
  
  build-eventapi:
    runs-on: windows-latest
    needs: unittest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: cd Services/Wingrid.Services.EventAPI && dotnet build --configuration Release

      - name: dotnet publish
        run: cd Services/Wingrid.Services.EventAPI && dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/wingridEventAPI

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: wingridEventAPI-app
          path: ${{env.DOTNET_ROOT}}/wingridEventAPI
  
  build-fixtureapi:
    runs-on: windows-latest
    needs: unittest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: cd Services/Wingrid.Services.FixtureAPI && dotnet build --configuration Release

      - name: dotnet publish
        run: cd Services/Wingrid.Services.FixtureAPI && dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/wingridFixtureAPI

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: wingridFixtureAPI-app
          path: ${{env.DOTNET_ROOT}}/wingridFixtureAPI

  deploy-auth:
    runs-on: windows-latest
    needs: build-auth
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: winGridAuthAPI-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'WingridAuthAPI'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BB2A031FE29C4B97A61BFF013C0A2A6F }}
          package: .
  
  deploy-eventapi:
    runs-on: windows-latest
    needs: build-eventapi
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: wingridEventAPI-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'wingridEventAPI'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9BEEEBCA43AC45B5B5C66CABAC7C9BF2 }}
          package: .

  deploy-fixtureapi:
    runs-on: windows-latest
    needs: build-fixtureapi
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: wingridFixtureAPI-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'wingridFixtureAPI'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6A2AC4F4F176402181F0B7378A711D0C }}
          package: .
